"""add entity_image table

Revision ID: 2adedf658d09
Revises: 399431cbe212
Create Date: 2026-08-24 13:49:10.285206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adedf658d09'
down_revision: Union[str, Sequence[str], None] = '399431cbe212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('cover', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_image_cover', 'entity_image', ['entity_id'], unique=True, postgresql_where=sa.text('cover'))
    op.create_index('ix_entity_image_entity', 'entity_image', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_image_entity', table_name='entity_image')
    op.drop_index('ix_entity_image_cover', table_name='entity_image', postgresql_where=sa.text('cover'))
    op.drop_table('entity_image')
    # ### end Alembic commands ###
