"""add owner_id to entities

Revision ID: 3cb0a9e19f8c
Revises: 44167d6ef111
Create Date: 2026-09-17 13:41:25.281599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb0a9e19f8c'
down_revision: Union[str, Sequence[str], None] = '44167d6ef111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.execute("UPDATE entities SET owner_id = (select id from users where name = 'dev')")
    op.alter_column('entities', 'owner_id', nullable=False)
    op.create_foreign_key('entities_owner_id_fkey', 'entities', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entities_owner_id_fkey', 'entities', type_='foreignkey')
    op.drop_column('entities', 'owner_id')
    # ### end Alembic commands ###
