"""add gloss to relationship

Revision ID: 6c2c163a7084
Revises: 2adedf658d09
Create Date: 2026-09-03 11:36:44.459549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2c163a7084'
down_revision: Union[str, Sequence[str], None] = '2adedf658d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationship', sa.Column('gloss', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationship', 'gloss')
    # ### end Alembic commands ###
