"""create phase 1 tables

Revision ID: c32c139567d1
Revises: 
Create Date: 2026-08-08 15:23:55.628793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c32c139567d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('source_id != target_id'),
    sa.CheckConstraint('weight BETWEEN 1 AND 3'),
    sa.ForeignKeyConstraint(['source_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'label')
    )
    op.create_index('ix_relationship_source', 'relationship', ['source_id'], unique=False)
    op.create_index('ix_relationship_target', 'relationship', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationship_target', table_name='relationship')
    op.drop_index('ix_relationship_source', table_name='relationship')
    op.drop_table('relationship')
    op.drop_table('entity')
    op.drop_table('entity_type')
    # ### end Alembic commands ###
